[package]
name = "bot-against-humanity-cli-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bot-against-humanity-core = { path = "../core" }
